/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version information, fields, and population totals */
        get: operations["getDataset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dsl/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parse a condition string into an AST */
        get: operations["parseCondition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dsl/serialize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Serialize an AST into a condition string */
        post: operations["serializeCondition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dsl/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply the clauses of an aggregation element to a condition
         * @description In `toggle` mode, adds each clause to the condition: joined with OR into the top-level clause group of the same field when one exists, otherwise as a new AND conjunct. When every clause is already present, the clauses are removed instead. In `narrow` mode, adds each clause as a new AND conjunct; with the population of an aggregation as `q`, the result matches the BioSamples or experiments counted by the element.
         */
        post: operations["selectElement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dsl/keyword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace the keywords of a condition
         * @description Replaces the keywords among the top-level AND conjuncts of `q` with the keywords of `keyword`, read as a search box reads text: quoted parts are phrases, and the other words form one keyword. `AND`, `OR`, and `NOT` are ordinary words. An empty `keyword` removes the keywords.
         */
        post: operations["setKeyword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** BioSample entries that match the condition */
        get: operations["listEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/biosample/{accession}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A BioSample with its annotations and evidence */
        get: operations["getEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Counts per element of one dimension
         * @description Elements default to the terms most often annotated directly, followed by the elements that the condition names, ordered by their count with descendants. For an annotation field the response also carries the status composition of the field, computed without the conjuncts on the field's term and status dimensions.
         */
        get: operations["getDistribution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crosstab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts per cell of two dimensions with expected counts */
        get: operations["getCrosstab"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Counts of the condition per BioSample creation year
         * @description `total` counts the condition per year, computed without the conjuncts on `date_created`. When `field` is given, `series` counts each element of that dimension per year, computed without the conjuncts on that dimension as well.
         */
        get: operations["getTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** BioProjects of the matching BioSamples */
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search the terms annotated in a field, or in every annotation field
         * @description Each hit is counted in the population of its own field: with `facetSelfExclude`, the condition without the conjuncts on that field.
         */
        get: operations["searchTerms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terms/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Child terms of a term annotated in a field */
        get: operations["listTermChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/accessions/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accession list of the matching entries, one per line */
        get: operations["exportAccessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/entries/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matching entries as TSV or newline-delimited JSON */
        get: operations["exportEntries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get service information
         * @description The name, the version, and the state of the store. Returns 200 whether or not the store is available; `store` reports the actual state. Intended for health monitoring.
         */
        get: operations["getServiceInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnnotationValue */
        AnnotationValue: {
            /** Value */
            value: string | null;
            /** Status */
            status: string;
            /** Termid */
            termId: string | null;
            /** Label */
            label: string | null;
        };
        /** Attribute */
        Attribute: {
            /** Name */
            name: string;
            /** Value */
            value: string;
            /** Harmonizedname */
            harmonizedName: string | null;
        };
        /** Cell */
        Cell: {
            /** Row */
            row: string;
            /** Col */
            col: string;
            /** Count */
            count: number;
            /** Expected */
            expected: number | null;
            /** Residual */
            residual: number | null;
            /** Classification */
            classification: ("gap" | "under" | "over") | null;
        };
        /**
         * Clause
         * @description One DSL clause, as `field` with `value` or with a date range `from`/`to`.
         */
        "Clause-Input": {
            /** Field */
            field: string;
            /** Value */
            value?: string | null;
            /** From */
            from?: string | null;
            /** To */
            to?: string | null;
        };
        "Clause-Output": components["schemas"]["ClauseJson"];
        /** ClauseJson */
        ClauseJson: {
            /** Field */
            field: string;
            /** Value */
            value?: string;
            /** From */
            from?: string;
            /** To */
            to?: string;
        };
        /** ConditionResponse */
        ConditionResponse: {
            datasetVersion: components["schemas"]["DatasetVersionRef"];
            /**
             * Dsl
             * @description The condition string
             */
            dsl: string | null;
            /** Ast */
            ast: {
                [key: string]: unknown;
            } | null;
            /**
             * Labels
             * @description Display labels of the term IDs and organism IDs used in the condition
             */
            labels: {
                [key: string]: string;
            };
        };
        /** CrosstabResponse */
        CrosstabResponse: {
            datasetVersion: components["schemas"]["DatasetVersionRef"];
            /** Q */
            q: string | null;
            /** Populationq */
            populationQ: string | null;
            /** Rowfield */
            rowField: string;
            /** Colfield */
            colField: string;
            unit: components["schemas"]["Unit"];
            /** Facetselfexclude */
            facetSelfExclude: boolean;
            /** Total */
            total: number;
            /** Rows */
            rows: (components["schemas"]["TermElement"] | components["schemas"]["Element"])[];
            /** Cols */
            cols: (components["schemas"]["TermElement"] | components["schemas"]["Element"])[];
            /** Cells */
            cells: components["schemas"]["Cell"][];
        };
        /** DatasetOrganism */
        DatasetOrganism: {
            /**
             * Identifier
             * @description NCBI Taxonomy ID
             */
            identifier: string;
            /** Name */
            name: string | null;
            /** Biosamplecount */
            biosampleCount: number;
        };
        /** DatasetResponse */
        DatasetResponse: {
            datasetVersion: components["schemas"]["DatasetVersionRef"];
            /**
             * Version
             * @description Full dataset version information
             */
            version: {
                [key: string]: unknown;
            };
            /** Targetassays */
            targetAssays: string[];
            /** Fields */
            fields: components["schemas"]["FieldDescription"][];
            /** Dslfields */
            dslFields: components["schemas"]["DslFieldDescription"][];
            /**
             * Statuses
             * @description Status groups and the statuses under them
             */
            statuses: {
                [key: string]: string[];
            };
            totals: components["schemas"]["Totals"];
            /** Organisms */
            organisms: components["schemas"]["DatasetOrganism"][];
        };
        /**
         * DatasetVersionRef
         * @description Identifies the store a response was computed from. Full details are returned by the dataset endpoint.
         */
        DatasetVersionRef: {
            /** Name */
            name: string;
            /** Createdat */
            createdAt: string;
            /** Model */
            model: string;
            /**
             * Digest
             * @description Short hash of the full version information
             */
            digest: string;
        };
        /** DistributionResponse */
        DistributionResponse: {
            datasetVersion: components["schemas"]["DatasetVersionRef"];
            /** Q */
            q: string | null;
            /**
             * Populationq
             * @description The condition the counts were computed from
             */
            populationQ: string | null;
            /** Field */
            field: string;
            unit: components["schemas"]["Unit"];
            /** Facetselfexclude */
            facetSelfExclude: boolean;
            /**
             * Total
             * @description Count of the population in the unit
             */
            total: number;
            /** Elements */
            elements: (components["schemas"]["TermElement"] | components["schemas"]["Element"])[];
            /**
             * Status
             * @description Status counts for annotation fields
             */
            status?: components["schemas"]["Element"][] | null;
            /** Statuspopulationq */
            statusPopulationQ?: string | null;
        };
        /** DslFieldDescription */
        DslFieldDescription: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Operators */
            operators: string[];
        };
        /** Element */
        Element: {
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Clauses */
            clauses: components["schemas"]["Clause-Output"][];
            /** Count */
            count: number;
        };
        /** EntriesResponse */
        EntriesResponse: {
            datasetVersion: components["schemas"]["DatasetVersionRef"];
            /** Q */
            q: string | null;
            type: components["schemas"]["EntryType"];
            pagination: components["schemas"]["Pagination"];
            /** Items */
            items: components["schemas"]["EntryItem"][];
        };
        /** EntryAnnotation */
        EntryAnnotation: {
            /** Field */
            field: string;
            /** Value */
            value: string | null;
            /** Status */
            status: string;
            /** Termid */
            termId: string | null;
            /** Label */
            label: string | null;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** EntryBioProject */
        EntryBioProject: {
            /** Accession */
            accession: string;
            /** Title */
            title: string | null;
        };
        /** EntryExperiment */
        EntryExperiment: {
            /** Accession */
            accession: string;
            /** Librarystrategy */
            libraryStrategy: string | null;
            /** Inpopulation */
            inPopulation: boolean;
            /** Runs */
            runs: string[];
            /** Chipatlas */
            chipAtlas: string[];
        };
        /** EntryItem */
        EntryItem: {
            /**
             * Identifier
             * @description BioSample accession
             */
            identifier: string;
            type: components["schemas"]["EntryType"];
            /**
             * Experiments
             * @description Experiments of the BioSample that match the condition
             */
            experiments: string[];
            /** Title */
            title: string | null;
            organism: components["schemas"]["Organism"] | null;
            /** Librarystrategy */
            libraryStrategy: string[];
            /** Bioprojects */
            bioprojects: string[];
            /** Datecreated */
            dateCreated: string | null;
            /**
             * Chipatlas
             * @description Genome assemblies under which ChIP-Atlas processed the experiments
             */
            chipAtlas: string[];
            /** Annotations */
            annotations: {
                [key: string]: components["schemas"]["AnnotationValue"][];
            };
        };
        /** EntryResponse */
        EntryResponse: {
            datasetVersion: components["schemas"]["DatasetVersionRef"];
            /**
             * Identifier
             * @description BioSample accession
             */
            identifier: string;
            /**
             * Type
             * @constant
             */
            type: "biosample";
            /** Title */
            title: string | null;
            organism: components["schemas"]["Organism"] | null;
            /** Datecreated */
            dateCreated: string | null;
            /** Datemodified */
            dateModified: string | null;
            /** Run */
            run: string;
            /** Attributes */
            attributes: components["schemas"]["Attribute"][];
            /** Annotations */
            annotations: components["schemas"]["EntryAnnotation"][];
            /** Experiments */
            experiments: components["schemas"]["EntryExperiment"][];
            /** Bioprojects */
            bioprojects: components["schemas"]["EntryBioProject"][];
        };
        /** @constant */
        EntryType: "biosample";
        /** Evidence */
        Evidence: {
            /**
             * Attribute
             * @description Attribute name, or `title` for the BioSample title
             */
            attribute: string;
            /**
             * Attributeindex
             * @description Position in `attributes`, or -1 for the title
             */
            attributeIndex: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Method */
            method: string;
        };
        /** FieldDescription */
        FieldDescription: {
            /** Name */
            name: string;
            /** Multivalued */
            multiValued: boolean;
            /** Ontologies */
            ontologies: string[];
        };
        /** KeywordRequest */
        KeywordRequest: {
            /** Q */
            q?: string | null;
            /**
             * Keyword
             * @description Text as typed into a keyword box: words, and phrases in double quotes. An empty keyword removes the keywords of the condition.
             */
            keyword: string;
        };
        /**
         * Organism
         * @description An organism as the NCBI Taxonomy ID and the name.
         */
        Organism: {
            /**
             * Identifier
             * @description NCBI Taxonomy ID
             */
            identifier: string;
            /** Name */
            name: string | null;
        };
        /** Pagination */
        Pagination: {
            /** Page */
            page: number;
            /** Perpage */
            perPage: number;
            /** Total */
            total: number;
            /** Hasnext */
            hasNext: boolean;
        };
        /** ParseResponse */
        ParseResponse: {
            datasetVersion: components["schemas"]["DatasetVersionRef"];
            /** Q */
            q: string;
            /** Ast */
            ast: {
                [key: string]: unknown;
            };
            /**
             * Labels
             * @description Display labels of the term IDs and organism IDs used in the condition
             */
            labels: {
                [key: string]: string;
            };
        };
        /**
         * ProblemDetails
         * @description RFC 7807 problem details of an error response.
         */
        ProblemDetails: {
            /**
             * Type
             * @description `about:blank`, or a URI that identifies an error specific to the api
             */
            type: string;
            /**
             * Title
             * @description The HTTP status phrase
             */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /**
             * Instance
             * @description The path of the request
             */
            instance: string;
            /**
             * Timestamp
             * @description ISO 8601 time in UTC
             */
            timestamp: string;
            /**
             * Requestid
             * @description The value of the `X-Request-ID` header of the response
             */
            requestId: string;
        };
        /** Project */
        Project: {
            /**
             * Identifier
             * @description BioProject accession
             */
            identifier: string;
            /** Title */
            title: string | null;
            /** Biosamplecount */
            biosampleCount: number;
            /** Experimentcount */
            experimentCount: number;
            /** Assays */
            assays: string[];
            /** Clauses */
            clauses: components["schemas"]["Clause-Output"][];
        };
        /** @enum {string} */
        ProjectSort: "biosampleCount:desc" | "biosampleCount:asc" | "experimentCount:desc" | "experimentCount:asc";
        /** ProjectsResponse */
        ProjectsResponse: {
            datasetVersion: components["schemas"]["DatasetVersionRef"];
            /** Q */
            q: string | null;
            /** Populationq */
            populationQ: string | null;
            /** Facetselfexclude */
            facetSelfExclude: boolean;
            /** Sort */
            sort: string;
            pagination: components["schemas"]["Pagination"];
            /** Items */
            items: components["schemas"]["Project"][];
        };
        /** SelectRequest */
        SelectRequest: {
            /** Q */
            q?: string | null;
            /** Clauses */
            clauses: components["schemas"]["Clause-Input"][];
            /**
             * Mode
             * @description `toggle` adds each clause, or removes the clauses when all of them are present. `narrow` adds each clause as a new AND conjunct.
             * @default toggle
             * @enum {string}
             */
            mode: "toggle" | "narrow";
        };
        /** SerializeRequest */
        SerializeRequest: {
            /** Ast */
            ast: {
                [key: string]: unknown;
            };
        };
        /** ServiceInfoResponse */
        ServiceInfoResponse: {
            /** Name */
            name: string;
            /**
             * Version
             * @description Package version, followed by `+<commit>` when the build records a commit
             */
            version: string;
            /** Description */
            description: string;
            /**
             * Store
             * @enum {string}
             */
            store: "ok" | "unavailable";
        };
        /** TermChildrenResponse */
        TermChildrenResponse: {
            datasetVersion: components["schemas"]["DatasetVersionRef"];
            /** Field */
            field: string;
            /** Termid */
            termId: string;
            /** Populationq */
            populationQ: string | null;
            unit: components["schemas"]["Unit"];
            /** Children */
            children: components["schemas"]["TermElement"][];
        };
        /** TermElement */
        TermElement: {
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Clauses */
            clauses: components["schemas"]["Clause-Output"][];
            /** Count */
            count: number;
            /** Countexact */
            countExact: number;
            /** Countselected */
            countSelected: number;
            /** Haschildren */
            hasChildren: boolean;
        };
        /** TermHit */
        TermHit: {
            /** Field */
            field: string;
            /** Termid */
            termId: string;
            /** Label */
            label: string | null;
            /** Ontology */
            ontology: string;
            /**
             * Path
             * @description Labels of the ancestors along one path from a root, nearest last
             */
            path: string[];
            /**
             * Descendantcount
             * @description Descendant terms annotated in the population
             */
            descendantCount: number;
            /** Count */
            count: number;
            /** Clauses */
            clauses: components["schemas"]["Clause-Output"][];
        };
        /** TermsResponse */
        TermsResponse: {
            datasetVersion: components["schemas"]["DatasetVersionRef"];
            /**
             * Field
             * @description The searched field, or null when every annotation field was searched
             */
            field: string | null;
            /** Query */
            query: string;
            /**
             * Populationq
             * @description The condition the counts were computed from, or null when every annotation field was searched
             */
            populationQ: string | null;
            unit: components["schemas"]["Unit"];
            /** Terms */
            terms: components["schemas"]["TermHit"][];
        };
        /** Totals */
        Totals: {
            /** Biosample */
            biosample: number;
            /** Experiment */
            experiment: number;
            /** Bioproject */
            bioproject: number;
        };
        /** TrendPoint */
        TrendPoint: {
            /** Year */
            year: number;
            /** Count */
            count: number;
            /** Clauses */
            clauses: components["schemas"]["Clause-Output"][];
        };
        /** TrendResponse */
        TrendResponse: {
            datasetVersion: components["schemas"]["DatasetVersionRef"];
            /** Q */
            q: string | null;
            unit: components["schemas"]["Unit"];
            /** Facetselfexclude */
            facetSelfExclude: boolean;
            /** Years */
            years: number[];
            /**
             * Total
             * @description Counts of the condition per year
             */
            total: components["schemas"]["TrendPoint"][];
            /**
             * Totalpopulationq
             * @description The condition the counts of `total` were computed from
             */
            totalPopulationQ: string | null;
            /**
             * Field
             * @description The dimension of `series`, when the request names one
             */
            field: string | null;
            /**
             * Populationq
             * @description The condition the counts of `series` were computed from
             */
            populationQ: string | null;
            /** Series */
            series: components["schemas"]["TrendSeries"][];
        };
        /** TrendSeries */
        TrendSeries: {
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Clauses */
            clauses: components["schemas"]["Clause-Output"][];
            /** Points */
            points: components["schemas"]["TrendPoint"][];
        };
        /** @enum {string} */
        Unit: "biosample" | "sra-experiment" | "bioproject";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDataset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    parseCondition: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    serializeCondition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SerializeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    selectElement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    setKeyword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listEntries: {
        parameters: {
            query?: {
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                page?: number;
                perPage?: number;
            };
            header?: never;
            path: {
                type: "biosample";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntriesResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accession: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getDistribution: {
        parameters: {
            query: {
                field: string;
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                /** @description Counting unit */
                unit?: components["schemas"]["Unit"];
                /** @description Compute without the top-level conjuncts of `q` that are only on the dimensions of the aggregation */
                facetSelfExclude?: boolean;
                /** @description Comma-separated elements; omitted means the top elements */
                elements?: string | null;
                /** @description Number of elements when they are not named */
                limit?: number;
                /** @description For status dimensions, the six statuses instead of the three groups */
                expandedStatus?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistributionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getCrosstab: {
        parameters: {
            query: {
                row: string;
                col: string;
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                /** @description Counting unit */
                unit?: components["schemas"]["Unit"];
                /** @description Compute without the top-level conjuncts of `q` that are only on the dimensions of the aggregation */
                facetSelfExclude?: boolean;
                /** @description Comma-separated row elements; omitted means the top rows */
                rowElements?: string | null;
                /** @description Comma-separated column elements; omitted means the top columns */
                colElements?: string | null;
                /** @description Number of elements when they are not named */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrosstabResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getTrend: {
        parameters: {
            query?: {
                /** @description Dimension of the series; omitted means no series */
                field?: string | null;
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                /** @description Counting unit */
                unit?: components["schemas"]["Unit"];
                /** @description Compute without the top-level conjuncts of `q` that are only on the dimensions of the aggregation */
                facetSelfExclude?: boolean;
                /** @description Comma-separated elements; omitted means the top elements */
                elements?: string | null;
                /** @description Number of elements when they are not named */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: {
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                /** @description Compute without the top-level conjuncts of `q` that are only on the dimensions of the aggregation */
                facetSelfExclude?: boolean;
                sort?: components["schemas"]["ProjectSort"];
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    searchTerms: {
        parameters: {
            query?: {
                /** @description Annotation field; omitted means every annotation field */
                field?: string | null;
                /** @description Substring of a label, synonym, or term ID; empty lists the most annotated terms */
                query?: string;
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                unit?: components["schemas"]["Unit"];
                /** @description Compute without the top-level conjuncts of `q` that are only on the dimensions of the aggregation */
                facetSelfExclude?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermsResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    listTermChildren: {
        parameters: {
            query: {
                field: string;
                termId: string;
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                unit?: components["schemas"]["Unit"];
                /** @description Compute without the top-level conjuncts of `q` that are only on the dimensions of the aggregation */
                facetSelfExclude?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermChildrenResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    exportAccessions: {
        parameters: {
            query?: {
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
            };
            header?: never;
            path: {
                type: "biosample" | "sra-experiment" | "sra-run" | "bioproject";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    exportEntries: {
        parameters: {
            query?: {
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                format?: "tsv" | "ndjson";
            };
            header?: never;
            path: {
                type: "biosample";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    getServiceInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceInfoResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
