/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version information, fields, and population totals */
        get: operations["get_dataset_api_dataset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dsl/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Parse a condition string into an AST */
        get: operations["parse_dsl_api_dsl_parse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dsl/serialize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Serialize an AST into a condition string */
        post: operations["serialize_dsl_api_dsl_serialize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dsl/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Toggle the clauses of an aggregation element in a condition
         * @description Adds each clause to the condition: joined with OR into the top-level clause group of the same field when one exists, otherwise as a new AND conjunct. When every clause of the element is already present, the clauses are removed instead.
         */
        post: operations["select_dsl_api_dsl_select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matching records as BioSample or experiment rows */
        get: operations["get_records_api_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entries/{accession}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A BioSample with its annotations and evidence */
        get: operations["get_entry_api_entries__accession__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Counts per element of one dimension
         * @description Elements default to the terms most often annotated directly, ordered by their count with descendants. For an annotation field the response also carries the status composition of the field, computed without the conjuncts on the field's term and status dimensions.
         */
        get: operations["get_distribution_api_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/crosstab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts per cell of two dimensions with expected counts */
        get: operations["get_crosstab_api_crosstab_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Counts per element and BioSample creation year */
        get: operations["get_trend_api_trend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** BioProjects of the matching records */
        get: operations["get_projects_api_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the terms annotated in a field */
        get: operations["search_terms_api_terms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terms/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Child terms of a term annotated in a field */
        get: operations["term_children_api_terms_children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/accessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accession list of the matching records, one per line */
        get: operations["export_accessions_api_export_accessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matching records as TSV or JSON lines */
        get: operations["export_records_api_export_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnnotationValue */
        AnnotationValue: {
            /** Value */
            value: string | null;
            /** Status */
            status: string;
            /** Term Id */
            term_id: string | null;
            /** Label */
            label: string | null;
        };
        /** Attribute */
        Attribute: {
            /** Name */
            name: string;
            /** Value */
            value: string;
            /** Harmonized Name */
            harmonized_name: string | null;
        };
        /** Cell */
        Cell: {
            /** Row */
            row: string;
            /** Col */
            col: string;
            /** Count */
            count: number;
            /** Expected */
            expected: number | null;
            /** Residual */
            residual: number | null;
            /** Classification */
            classification: ("gap" | "under" | "over") | null;
        };
        /**
         * Clause
         * @description One DSL clause, as `field` with `value` or with a date range `from`/`to`.
         */
        "Clause-Input": {
            /** Field */
            field: string;
            /** Value */
            value?: string | null;
            /** From */
            from?: string | null;
            /** To */
            to?: string | null;
        };
        "Clause-Output": components["schemas"]["ClauseJson"];
        /** ClauseJson */
        ClauseJson: {
            /** Field */
            field: string;
            /** Value */
            value?: string;
            /** From */
            from?: string;
            /** To */
            to?: string;
        };
        /** Composition */
        Composition: {
            /** Field */
            field: string;
            /** Total */
            total: number;
            /** Segments */
            segments: components["schemas"]["CompositionSegment"][];
        };
        /** CompositionSegment */
        CompositionSegment: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "term" | "other" | "unmapped" | "no_value";
            /** Label */
            label: string | null;
            /** Term Id */
            term_id: string | null;
            /** Count */
            count: number;
        };
        /** ConditionResponse */
        ConditionResponse: {
            dataset_version: components["schemas"]["DatasetVersionRef"];
            /** Q */
            q: string | null;
            /** Ast */
            ast: {
                [key: string]: unknown;
            } | null;
            /**
             * Labels
             * @description Display labels of the term IDs and organism IDs used in the condition
             */
            labels: {
                [key: string]: string;
            };
        };
        /** CrosstabResponse */
        CrosstabResponse: {
            dataset_version: components["schemas"]["DatasetVersionRef"];
            /** Q */
            q: string | null;
            /** Population Q */
            population_q: string | null;
            /** Row Field */
            row_field: string;
            /** Col Field */
            col_field: string;
            unit: components["schemas"]["Unit"];
            /** Self Exclusion */
            self_exclusion: boolean;
            /** Total */
            total: number;
            /** Rows */
            rows: (components["schemas"]["TermElement"] | components["schemas"]["Element"])[];
            /** Cols */
            cols: (components["schemas"]["TermElement"] | components["schemas"]["Element"])[];
            /** Cells */
            cells: components["schemas"]["Cell"][];
        };
        /** DatasetResponse */
        DatasetResponse: {
            dataset_version: components["schemas"]["DatasetVersionRef"];
            /**
             * Version
             * @description Full dataset version information
             */
            version: {
                [key: string]: unknown;
            };
            /** Target Assays */
            target_assays: string[];
            /** Fields */
            fields: components["schemas"]["FieldDescription"][];
            /** Dsl Fields */
            dsl_fields: components["schemas"]["DslFieldDescription"][];
            /**
             * Statuses
             * @description Status groups and the statuses under them
             */
            statuses: {
                [key: string]: string[];
            };
            totals: components["schemas"]["Totals"];
            /** Organisms */
            organisms: components["schemas"]["Organism"][];
        };
        /**
         * DatasetVersionRef
         * @description Identifies the store a response was computed from. Full details are returned by the dataset endpoint.
         */
        DatasetVersionRef: {
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
            /** Model */
            model: string;
            /**
             * Digest
             * @description Short hash of the full version information
             */
            digest: string;
        };
        /** DistributionResponse */
        DistributionResponse: {
            dataset_version: components["schemas"]["DatasetVersionRef"];
            /** Q */
            q: string | null;
            /**
             * Population Q
             * @description The condition the counts were computed from
             */
            population_q: string | null;
            /** Field */
            field: string;
            unit: components["schemas"]["Unit"];
            /** Self Exclusion */
            self_exclusion: boolean;
            /**
             * Total
             * @description Count of the population in the unit
             */
            total: number;
            /** Elements */
            elements: (components["schemas"]["TermElement"] | components["schemas"]["Element"])[];
            /**
             * Status
             * @description Status counts for annotation fields
             */
            status?: components["schemas"]["Element"][] | null;
            /** Status Population Q */
            status_population_q?: string | null;
        };
        /** DslFieldDescription */
        DslFieldDescription: {
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Operators */
            operators: string[];
        };
        /** Element */
        Element: {
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Clauses */
            clauses: components["schemas"]["Clause-Output"][];
            /** Count */
            count: number;
        };
        /** EntryAnnotation */
        EntryAnnotation: {
            /** Field */
            field: string;
            /** Value */
            value: string | null;
            /** Status */
            status: string;
            /** Term Id */
            term_id: string | null;
            /** Label */
            label: string | null;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** EntryBioProject */
        EntryBioProject: {
            /** Accession */
            accession: string;
            /** Title */
            title: string | null;
        };
        /** EntryExperiment */
        EntryExperiment: {
            /** Accession */
            accession: string;
            /** Library Strategy */
            library_strategy: string | null;
            /** In Population */
            in_population: boolean;
            /** Runs */
            runs: string[];
            /** Chip Atlas */
            chip_atlas: string[];
        };
        /** EntryResponse */
        EntryResponse: {
            dataset_version: components["schemas"]["DatasetVersionRef"];
            /** Accession */
            accession: string;
            /** Title */
            title: string | null;
            /** Organism Id */
            organism_id: number | null;
            /** Organism Name */
            organism_name: string | null;
            /** Date Created */
            date_created: string | null;
            /** Date Modified */
            date_modified: string | null;
            /** Run */
            run: string;
            /** Attributes */
            attributes: components["schemas"]["Attribute"][];
            /** Annotations */
            annotations: components["schemas"]["EntryAnnotation"][];
            /** Experiments */
            experiments: components["schemas"]["EntryExperiment"][];
            /** Bioprojects */
            bioprojects: components["schemas"]["EntryBioProject"][];
        };
        /** Evidence */
        Evidence: {
            /**
             * Attribute
             * @description Attribute name, or `title` for the BioSample title
             */
            attribute: string;
            /**
             * Attribute Index
             * @description Position in `attributes`, or -1 for the title
             */
            attribute_index: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Method */
            method: string;
        };
        /** FieldDescription */
        FieldDescription: {
            /** Name */
            name: string;
            /** Multi Valued */
            multi_valued: boolean;
            /** Ontologies */
            ontologies: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Organism */
        Organism: {
            /** Organism Id */
            organism_id: number;
            /** Name */
            name: string | null;
            /** N Biosample */
            n_biosample: number;
        };
        /** ParseResponse */
        ParseResponse: {
            dataset_version: components["schemas"]["DatasetVersionRef"];
            /** Q */
            q: string;
            /** Ast */
            ast: {
                [key: string]: unknown;
            };
            /**
             * Labels
             * @description Display labels of the term IDs and organism IDs used in the condition
             */
            labels: {
                [key: string]: string;
            };
        };
        /** Project */
        Project: {
            /** Bioproject */
            bioproject: string;
            /** Title */
            title: string | null;
            /** N Biosample */
            n_biosample: number;
            /** N Experiment */
            n_experiment: number;
            /** Assays */
            assays: string[];
            /** Clauses */
            clauses: components["schemas"]["Clause-Output"][];
            /** Composition */
            composition: components["schemas"]["Composition"][];
        };
        /** @enum {string} */
        ProjectSort: "biosample" | "experiment" | "accession";
        /** ProjectsResponse */
        ProjectsResponse: {
            dataset_version: components["schemas"]["DatasetVersionRef"];
            /** Q */
            q: string | null;
            /** Population Q */
            population_q: string | null;
            /** Self Exclusion */
            self_exclusion: boolean;
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Sort */
            sort: string;
            /** Composition Fields */
            composition_fields: string[];
            /** Projects */
            projects: components["schemas"]["Project"][];
        };
        /** RecordRow */
        RecordRow: {
            /** Biosample */
            biosample: string;
            /**
             * Experiment
             * @description Set when rows are experiments
             */
            experiment: string | null;
            /**
             * Experiments
             * @description Experiments of the BioSample in the matching records
             */
            experiments: string[];
            /** Title */
            title: string | null;
            /** Organism Id */
            organism_id: number | null;
            /** Organism Name */
            organism_name: string | null;
            /** Library Strategy */
            library_strategy: string[];
            /** Bioprojects */
            bioprojects: string[];
            /** Date Created */
            date_created: string | null;
            /**
             * Chip Atlas
             * @description Genome assemblies under which ChIP-Atlas processed the experiments
             */
            chip_atlas: string[];
            /** Annotations */
            annotations: {
                [key: string]: components["schemas"]["AnnotationValue"][];
            };
        };
        /** @enum {string} */
        RecordUnit: "biosample" | "experiment";
        /** RecordsResponse */
        RecordsResponse: {
            dataset_version: components["schemas"]["DatasetVersionRef"];
            /** Q */
            q: string | null;
            unit: components["schemas"]["RecordUnit"];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Per Page */
            per_page: number;
            /** Records */
            records: components["schemas"]["RecordRow"][];
        };
        /** SelectRequest */
        SelectRequest: {
            /** Q */
            q?: string | null;
            /** Clauses */
            clauses: components["schemas"]["Clause-Input"][];
        };
        /** SerializeRequest */
        SerializeRequest: {
            /** Ast */
            ast: {
                [key: string]: unknown;
            };
        };
        /** TermChildrenResponse */
        TermChildrenResponse: {
            dataset_version: components["schemas"]["DatasetVersionRef"];
            /** Field */
            field: string;
            /** Term Id */
            term_id: string;
            /** Population Q */
            population_q: string | null;
            unit: components["schemas"]["Unit"];
            /** Children */
            children: components["schemas"]["TermElement"][];
        };
        /** TermElement */
        TermElement: {
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Clauses */
            clauses: components["schemas"]["Clause-Output"][];
            /** Count */
            count: number;
            /** Count Exact */
            count_exact: number;
            /** Count Selected */
            count_selected: number;
            /** Has Children */
            has_children: boolean;
        };
        /** TermHit */
        TermHit: {
            /** Term Id */
            term_id: string;
            /** Label */
            label: string | null;
            /** Ontology */
            ontology: string;
            /**
             * Path
             * @description Labels of the ancestors along one path from a root, nearest last
             */
            path: string[];
            /**
             * N Descendants
             * @description Descendant terms annotated in the population
             */
            n_descendants: number;
            /** Count */
            count: number;
            /** Clauses */
            clauses: components["schemas"]["Clause-Output"][];
        };
        /** TermsResponse */
        TermsResponse: {
            dataset_version: components["schemas"]["DatasetVersionRef"];
            /** Field */
            field: string;
            /** Query */
            query: string;
            /** Population Q */
            population_q: string | null;
            unit: components["schemas"]["Unit"];
            /** Terms */
            terms: components["schemas"]["TermHit"][];
        };
        /** Totals */
        Totals: {
            /** Biosample */
            biosample: number;
            /** Experiment */
            experiment: number;
            /** Bioproject */
            bioproject: number;
            /** Record */
            record: number;
        };
        /** TrendPoint */
        TrendPoint: {
            /** Year */
            year: number;
            /** Count */
            count: number;
            /** Clauses */
            clauses: components["schemas"]["Clause-Output"][];
        };
        /** TrendResponse */
        TrendResponse: {
            dataset_version: components["schemas"]["DatasetVersionRef"];
            /** Q */
            q: string | null;
            /** Population Q */
            population_q: string | null;
            /** Field */
            field: string;
            unit: components["schemas"]["Unit"];
            /** Self Exclusion */
            self_exclusion: boolean;
            /** Years */
            years: number[];
            /** Series */
            series: components["schemas"]["TrendSeries"][];
        };
        /** TrendSeries */
        TrendSeries: {
            /** Value */
            value: string;
            /** Label */
            label: string;
            /** Clauses */
            clauses: components["schemas"]["Clause-Output"][];
            /** Points */
            points: components["schemas"]["TrendPoint"][];
        };
        /** @enum {string} */
        Unit: "biosample" | "experiment" | "bioproject";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_dataset_api_dataset_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetResponse"];
                };
            };
        };
    };
    parse_dsl_api_dsl_parse_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serialize_dsl_api_dsl_serialize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SerializeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_dsl_api_dsl_select_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_records_api_records_get: {
        parameters: {
            query?: {
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                /** @description Row unit */
                unit?: components["schemas"]["RecordUnit"];
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entry_api_entries__accession__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accession: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_distribution_api_distribution_get: {
        parameters: {
            query: {
                field: string;
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                /** @description Counting unit */
                unit?: components["schemas"]["Unit"];
                /** @description Compute without the top-level conjuncts of q that are only on the aggregation's dimensions */
                self_exclusion?: boolean;
                /** @description Comma-separated elements; omitted means the top elements */
                elements?: string | null;
                /** @description Number of elements when they are not named */
                limit?: number;
                /** @description For status dimensions, the six statuses instead of the three groups */
                expanded_status?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistributionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crosstab_api_crosstab_get: {
        parameters: {
            query: {
                row: string;
                col: string;
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                /** @description Counting unit */
                unit?: components["schemas"]["Unit"];
                /** @description Compute without the top-level conjuncts of q that are only on the aggregation's dimensions */
                self_exclusion?: boolean;
                /** @description Comma-separated row elements; omitted means the top rows */
                row_elements?: string | null;
                /** @description Comma-separated column elements; omitted means the top columns */
                col_elements?: string | null;
                /** @description Number of elements when they are not named */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CrosstabResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trend_api_trend_get: {
        parameters: {
            query: {
                field: string;
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                /** @description Counting unit */
                unit?: components["schemas"]["Unit"];
                /** @description Compute without the top-level conjuncts of q that are only on the aggregation's dimensions */
                self_exclusion?: boolean;
                /** @description Comma-separated elements; omitted means the top elements */
                elements?: string | null;
                /** @description Number of elements when they are not named */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_projects_api_projects_get: {
        parameters: {
            query?: {
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                /** @description Ignore the bioproject clauses of q */
                self_exclusion?: boolean;
                sort?: components["schemas"]["ProjectSort"];
                page?: number;
                per_page?: number;
                /** @description Comma-separated annotation fields whose composition is returned */
                composition_fields?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_terms_api_terms_get: {
        parameters: {
            query: {
                field: string;
                /** @description Substring of a label, synonym, or term ID; empty lists the most annotated terms */
                query?: string;
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                unit?: components["schemas"]["Unit"];
                self_exclusion?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    term_children_api_terms_children_get: {
        parameters: {
            query: {
                field: string;
                term_id: string;
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                unit?: components["schemas"]["Unit"];
                self_exclusion?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermChildrenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_accessions_api_export_accessions_get: {
        parameters: {
            query: {
                kind: "biosample" | "experiment" | "run" | "bioproject";
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_records_api_export_records_get: {
        parameters: {
            query?: {
                /** @description Condition in the DSL. Omitted or empty means the whole population. */
                q?: string | null;
                unit?: components["schemas"]["RecordUnit"];
                format?: "tsv" | "json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
